version: '3.9'
services:
  mongo:
    image: mongo:7
    restart: always
    ports: ["27017:27017"]
    volumes:
      - mongo-data:/data/db
  api:
    build: ./server
    command: node src/index.js
    env_file:
      - ./server/.env.example
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    volumes:
      - ./server:/app
    working_dir: /app
  client:
    build: ./client
    ports:
      - "5173:5173"
    depends_on:
      - api
volumes:
  mongo-data:

